---

MotorIds:
  rightFrontMotor: 1
  leftFrontMotor: 2
  rightRearMotor: 3
  leftRearMotor: 4

Drive:
  rightFrontMotor:
    id: 1
    kf: 0.0
    kp: 0.0
    ki: 0.0
    kd: 0.0
    iZone: 0.0
    inverted: false
    quadEncoder: true

  leftFrontMotor:
    id: 2
    kf: 0.0
    kp: 0.0
    ki: 0.0
    kd: 0.0
    iZone: 0.0
    inverted: true
    quadEncoder: true

  leftRearMotor:
    id: 3
    follow: "{{ MotorIds['leftFrontMotor']}}"

  rightRearMotor:
    id: 4
    follow: "{{ MotorIds['rightFrontMotor']}}"
